version: '3'

services:
  web:
    container_name: products_command
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
